export const transmissionConfig = {
  meshPhysicalMaterial: false,
  transmissionSampler: false,
  backside: false,
  samples: 10,
  resolution: 2048,
  transmission: 1,
  roughness: 0,
  thickness: 1,
  ior: 1.2,
  chromaticAberration: 0.5,
  anisotropy: 0.1,
  distortion: 0.22,
  distortionScale: 0.3,
  temporalDistortion: 0.5,
  clearcoat: 1,
  attenuationDistance: 0.5,
  attenuationColor: "#ffffff",
  color: "#ffffff",
};
