/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Dragon(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/dragon.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.dragon.geometry}>
        <meshStandardMaterial color={"#F8F8FF"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/dragon.gltf");
